name: Vault

services:
  node1: &node-default
    image: hashicorp/vault:${VAULT_VERSION}
    container_name: node1
    volumes:
      - vault-node1-logs:/vault/logs:rw
      - vault-node1-raft:/vault/raft:rw
      - ./node1/:/vault/config:rw
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8221:8221"
    networks:
      - nginx-proxy-manager_frontend
      - backend
    command:
      - server
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.node1-vault.rule=Host(`${NODE1_FQDN}`)
      - traefik.http.routers.node1-vault.middlewares=ipallowlocal@docker
      - traefik.http.services.node1-vault.Loadbalancer.server.port=8221
    cap_add:
      - IPC_LOCK

  node2:
    <<: *node-default
    container_name: node2
    volumes:
      - vault-node2-logs:/vault/logs:rw
      - vault-node2-raft:/vault/raft:rw
      - ./node2/:/vault/config:rw
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8222:8222"
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.node2-vault.rule=Host(`${NODE2_FQDN}`)
      - traefik.http.routers.node2-vault.middlewares=ipallowlocal@docker
      - traefik.http.services.node2-vault.Loadbalancer.server.port=8222

  node3:
    <<: *node-default
    container_name: node3
    volumes:
      - vault-node3-logs:/vault/logs:rw
      - vault-node3-raft:/vault/raft:rw
      - ./node3/:/vault/config:rw
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8223:8223"
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.node3-vault.rule=Host(`${NODE3_FQDN}`)
      - traefik.http.routers.node3-vault.middlewares=ipallowlocal@docker
      - traefik.http.services.node3-vault.Loadbalancer.server.port=8223

networks:
  nginx-proxy-manager_frontend:
    external: true
    driver: bridge
  backend:
    external: true
    driver: bridge

volumes:
  vault-node1-logs:
  vault-node1-raft:
  vault-node2-logs:
  vault-node2-raft:
  vault-node3-logs:
  vault-node3-raft:
